{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/Networking\/documentation\/Networking\/NetworkError\/underlying(error:)","interfaceLanguage":"swift"},"abstract":[{"text":"An indication of an underlaying network layer error.","type":"text"}],"metadata":{"title":"NetworkError.underlying(error:)","externalID":"s:10Networking12NetworkErrorO10underlyingyACs0C0_p_tcACmF","symbolKind":"case","role":"symbol","roleHeading":"Case","modules":[{"name":"Networking"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlying"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlying"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/networking\/networkerror\/underlying(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/Networking\/documentation\/Networking","doc:\/\/Networking\/documentation\/Networking\/NetworkError"]]},"kind":"symbol","references":{"doc://Networking/documentation/Networking/NetworkError":{"url":"\/documentation\/networking\/networkerror","title":"NetworkError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NetworkError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/Networking\/documentation\/Networking\/NetworkError","abstract":[{"type":"text","text":"An error that occurs during "},{"identifier":"doc:\/\/Networking\/documentation\/Networking\/Response","type":"reference","isActive":true},{"type":"text","text":" processing or an underlaying "},{"type":"reference","identifier":"doc:\/\/Networking\/documentation\/Networking","isActive":true},{"text":" error.","type":"text"}]},"doc://Networking/documentation/Networking":{"url":"\/documentation\/networking","role":"collection","identifier":"doc:\/\/Networking\/documentation\/Networking","type":"topic","abstract":[],"title":"Networking","kind":"symbol"},"doc://Networking/documentation/Networking/Response":{"url":"\/documentation\/networking\/response","title":"Response","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Response"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Response"}],"kind":"symbol","abstract":[{"type":"text","text":"A default "},{"type":"codeVoice","code":"URLSession"},{"type":"text","text":" response tuple."}],"identifier":"doc:\/\/Networking\/documentation\/Networking\/Response"},"doc://Networking/documentation/Networking/NetworkError/underlying(error:)":{"role":"symbol","type":"topic","url":"\/documentation\/networking\/networkerror\/underlying(error:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlying"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/Networking\/documentation\/Networking\/NetworkError\/underlying(error:)","abstract":[{"text":"An indication of an underlaying network layer error.","type":"text"}],"kind":"symbol","title":"NetworkError.underlying(error:)"}}}