{"sections":[],"metadata":{"externalID":"s:10Networking12NetworkErrorO7unknownyA2CmF","modules":[{"name":"Networking"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"NetworkError.unknown"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/networking\/networkerror\/unknown"]}],"identifier":{"url":"doc:\/\/Networking\/documentation\/Networking\/NetworkError\/unknown","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/Networking\/documentation\/Networking","doc:\/\/Networking\/documentation\/Networking\/NetworkError"]]},"abstract":[{"text":"An indication of an unknown cause.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://Networking/documentation/Networking/NetworkError":{"title":"NetworkError","abstract":[{"type":"text","text":"An error that occurs during "},{"type":"reference","identifier":"doc:\/\/Networking\/documentation\/Networking\/Response","isActive":true},{"type":"text","text":" processing or an underlaying "},{"identifier":"doc:\/\/Networking\/documentation\/Networking","isActive":true,"type":"reference"},{"type":"text","text":" error."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/Networking\/documentation\/Networking\/NetworkError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NetworkError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/networking\/networkerror","navigatorTitle":[{"kind":"identifier","text":"NetworkError"}]},"doc://Networking/documentation/Networking/NetworkError/unknown":{"url":"\/documentation\/networking\/networkerror\/unknown","kind":"symbol","abstract":[{"text":"An indication of an unknown cause.","type":"text"}],"type":"topic","title":"NetworkError.unknown","role":"symbol","identifier":"doc:\/\/Networking\/documentation\/Networking\/NetworkError\/unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]},"doc://Networking/documentation/Networking/Response":{"type":"topic","abstract":[{"type":"text","text":"A default "},{"code":"URLSession","type":"codeVoice"},{"type":"text","text":" response tuple."}],"title":"Response","role":"symbol","navigatorTitle":[{"text":"Response","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Response","kind":"identifier"}],"identifier":"doc:\/\/Networking\/documentation\/Networking\/Response","url":"\/documentation\/networking\/response"},"doc://Networking/documentation/Networking":{"abstract":[],"role":"collection","url":"\/documentation\/networking","type":"topic","kind":"symbol","identifier":"doc:\/\/Networking\/documentation\/Networking","title":"Networking"}}}